name: Build and Rename APK
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android
        run: |
          # Use the correct folder name 'qubeeapp'
          cd qubeeapp/app/android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Rename and Upload
        run: |
          chmod +x ./qubeeapp/app/rename_apk.sh
          # Updated all paths to include 'qubeeapp' prefix
          ./qubeeapp/app/rename_apk.sh QubeeApp qubeeapp/app/android/app/build/outputs/apk/release ./qubeeapp/app/pubspec.yaml
        shell: bash

      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: QubeeApp-Final
          path: qubeeapp/app/android/app/build/outputs/apk/release/*.apk
